services:
  app:
    image: ${APP_IMAGE:-{{cookiecutter.project_slug}}-app:latest}
    container_name: ${APP_CONTAINER_NAME:-{{cookiecutter.project_slug}}-app}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8080}:8080"
    volumes:
      - app_logs:/app/logs
    restart: unless-stopped

volumes:
  app_logs:
    driver: local
